apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
  - name: web
    image: montoyita41/proyecto:2024-05-15T11-26-36
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 250m
      limits:
        cpu: 500m
  
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: web  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
 

