apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: web
        image: montoyita41/proyecto:2024-05-13T23-21-19
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: web
  name: web
spec:
  rules:
  - host: porfavorserver.example.com
    http:
      paths:
      - backend:
          service:
            name: web
            port:
              number: 8000
        path: /*


