apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: web
        image: montoyita41/proyecto:2024-05-13T23-21-19
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m


---
kind: Service
metadata:
  name: helloweb
  labels:
    app: web
spec:
  selector:
    app: web
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 104.211.2.191
