name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 build:
    runs-on: ubuntu-latest
    outputs:
      tag_id: ${{ steps.date.outputs.date }}

    steps:
    - uses: actions/checkout@v4
    - name: Get timestamp # get the date of the build
      id: date
      run: echo "date=$(TZ=':America/Bogota' date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag montoyita41/proyecto:${{ steps.date.outputs.date }}
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image to Dockerhub
      run: docker push montoyita41/proyecto:${{ steps.date.outputs.date }}

 deploykubernetes:
    runs-on: ubuntu-latest
    steps:
#/      - uses: actions/checkout@v4
   #     - name: Run Terraform
  #        run: |
  #          set -e 
  #          cd terraform
   #        terraform init -input=false
   #         terraform apply -input=false -auto-approve
  #        env:
   #         ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
 #           ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
 #         ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}


      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account set --subscription 83c62e88-35c0-4f8d-8636-f21914cc6d80
  
