name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


 deploykubernetes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Add /usr/local/bin to PATH
      run: |
        export PATH="/usr/local/bin:$PATH"
    - uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
    
    - name: Checkout código
      uses: actions/checkout@v2
    
    - name: Azure CLI script
      uses: azure/cli@v2
      env:
        TAG_ID: ${{ steps.date.outputs.tag_id }}
      with:
        azcliversion: latest
        inlineScript: |
          az aks install-cli
          PIP_RESOURCE_GROUP=travel-rg
          AKS_RESOURCE_GROUP=travel-rg
          AKS_CLUSTER_NAME=kubernetes-travel
          CLIENT_ID=$(az aks show --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --query "servicePrincipalProfile.clientId" --output tsv)
          SUB_ID=$(az account show --query "id" --output tsv) 
          az role assignment create\
              --assignee $CLIENT_ID \
              --role "Network Contributor" \
              --scope /subscriptions/$SUB_ID/resourceGroups/$PIP_RESOURCE_GROUP
          az account set --subscription 83c62e88-35c0-4f8d-8636-f21914cc6d80
          az aks get-credentials --resource-group travel-rg --name kubernetes-travel --overwrite-existing
          kubectl apply -f terraform/k8s/api-deployment.yml  --validate=false  
          sleep 30s && kubectl get service

