name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


 deploykubernetes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Add /usr/local/bin to PATH
      run: |
        export PATH="/usr/local/bin:$PATH"
    - uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
    
    - name: Checkout código
      uses: actions/checkout@v2
    
    - name: Azure CLI script
      uses: azure/cli@v2
      env:
        TAG_ID: ${{ steps.date.outputs.tag_id }}
      with:
        azcliversion: latest
        inlineScript: |
          az aks install-cli
          az network public-ip create \
          --resource-group travel-rg \
          --name TRAVEL-PIP \
          --allocation-method static
          az account set --subscription 83c62e88-35c0-4f8d-8636-f21914cc6d80
          az aks get-credentials --resource-group travel-rg --name kubernetes-travel --overwrite-existing
          kubectl apply -f terraform/k8s/api-deployment.yml  --validate=false  
          sleep 30s && kubectl get service

